version: "3"
services:

  picocart:
    container_name: picocart
    image: node:11.5.0-alpine
    volumes:
      - .:/picocart
    working_dir: /picocart
    entrypoint: npm run dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://picocart:swordfish@postgres:5432/picocart

  postgres:
    container_name: postgres
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: picocart
      POSTGRES_PASSWORD: swordfish
      POSTGRES_DB: picocart

  storybook:
    container_name: storybook
    image: node:11.5.0-alpine
    volumes:
      - .:/picocart
    working_dir: /picocart
    entrypoint: npm run storybook-start
    ports:
      - "3001:3001"
