version: "3"
services:
  storybook:
    container_name: storybook
    image: node:11.5.0-alpine
    volumes:
      - .:/picocart
    working_dir: /picocart
    entrypoint: npm run storybook-start
    ports:
      - "3001:3001"
